//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarragoWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Farrago584Entities : DbContext
    {
        public Farrago584Entities()
            : base("name=Farrago584Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<LocalRequirements> LocalRequirements { get; set; }
        public virtual DbSet<LocalReservation> LocalReservation { get; set; }
        public virtual DbSet<Requirements> Requirements { get; set; }
        public virtual DbSet<TableReservation> TableReservation { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
