//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarragoWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalReservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocalReservation()
        {
            this.LocalRequirements = new HashSet<LocalRequirements>();
        }
    
        public int id { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
        public int PersonsNumber { get; set; }
        public string Confirmation { get; set; }
        public Nullable<int> AdminId { get; set; }
        public string UserObservation { get; set; }
        public string AdminObservation { get; set; }
        public double FinalPrice { get; set; }
        public string Status { get; set; }
    
        public virtual Admin Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalRequirements> LocalRequirements { get; set; }
        public virtual User User { get; set; }
    }
}
